version: '3.9'

services:
  db:
    image: 'mariadb:11.2.3-jammy'
    restart: always
    container_name: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE_NAME: phone_shop
    volumes:
      - ./tmp/db:/var/lib/mysql:Z
    ports:
      - 3306:3306
    networks:
      - phone-shop
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - phone-shop
  php-fpm:
    build: php/8.2-fpm
    container_name: php
    volumes:
        - ./../:/var/www/html
    networks:
      - phone-shop

networks:
  phone-shop:
    driver: bridge